export default function Head() {
  return (
    <Head>
      <title>m0rgause</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
